FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Minha Comunidade API
Recursos para as pessoas que vivem em comunidades poderem utilizar serviços administrativos e consumir produtos e serviços diversos para o seu dia-a-dia.

# Group Comunidades

## Comunidades Collection [/comunidades?{offsize}&{limit}]

### GET
+ Parameters
    + offsize (optional, number) ... Maximum number of posts to retrieve
    + limit (optional, number) ... Maximum number of posts to retrieve

+ Response 200 (application/json)
    + Attributes
        - comunidades (array[Comunidade Full])

### POST

+ Request (application/json)
    + Attributes
        - comunidades (Comunidade Create)

+ Response 200 (application/json)
    + Attributes
        - comunidades (Comunidade Full)

## Comunidade Resource [/comunidades/{id}]

+ Parameters
  + id: 1 - The unique ID of the comunidade.

### GET

+ Response 200 (application/json)
    + Attributes
        - comunidades (Comunidade Full)

### PUT

+ Request (application/json)
    + Attributes
        - comunidades (Comunidade Full)

+ Response 200 (application/json)
    + Attributes
        - comunidades (Comunidade Full)

### PATCH

+ Request (application/json)
    + Attributes
        - comunidades (Comunidade Full)

+ Response 204 (application/json)

### DELETE

+ Response 204

# Group Categorias

## Categorias Collection [/categorias]

### GET

+ Response 200 (application/json)
    + Attributes
        - categorias (array[Categoria Full])

### POST

+ Request (application/json)
    + Attributes
        - categorias (Categoria Create)

+ Response 200 (application/json)
    + Attributes
        - categorias (Categoria Full)

## Categoria Resource [/categorias/{id}]

+ Parameters
  + id: 1 - The unique ID of the categoria.

### GET

+ Response 200 (application/json)
    + Attributes
        - categorias (Categoria Full)

### PUT

+ Request (application/json)
    + Attributes
        - categorias (Categoria Full)

+ Response 200 (application/json)
    + Attributes
        - categorias (Categoria Full)

### PATCH

+ Request (application/json)
    + Attributes
        - categorias (Categoria Full)

+ Response 204 (application/json)

### DELETE

+ Response 204







# Group Produtos

## Produtos Collection [/produtos]

### GET

+ Response 200 (application/json)
    + Attributes
        - produtos (array[Produto Full])

### POST

+ Request (application/json)
    + Attributes
        - produtos (Produto Create)

+ Response 200 (application/json)
    + Attributes
        - produtos (Produto Full)

## Produto Resource [/produtos/{id}]

+ Parameters
  + id: 1 - The unique ID of the produto.

### GET

+ Response 200 (application/json)
    + Attributes
        - produtos (Produto Full)

### PUT

+ Request (application/json)
    + Attributes
        - produtos (Produto Full)

+ Response 200 (application/json)
    + Attributes
        - produtos (Produto Full)

### PATCH

+ Request (application/json)
    + Attributes
        - produtos (Produto Full)

+ Response 204 (application/json)

### DELETE

+ Response 204




# Group Servicos

## Servicos Collection [/servicos]

### GET

+ Response 200 (application/json)
    + Attributes
        - servicos (array[Servico Full])

### POST

+ Request (application/json)
    + Attributes
        - servicos (Servico Create)

+ Response 200 (application/json)
    + Attributes
        - servicos (Servico Full)

## Servico Resource [/servicos/{id}]

+ Parameters
  + id: 1 - The unique ID of the servico.

### GET

+ Response 200 (application/json)
    + Attributes
        - servicos (Servico Full)

### PUT

+ Request (application/json)
    + Attributes
        - servicos (Servico Full)

+ Response 200 (application/json)
    + Attributes
        - servicos (Servico Full)

### PATCH

+ Request (application/json)
    + Attributes
        - servicos (Servico Full)

+ Response 204 (application/json)

### DELETE

+ Response 204




# Group Pedidos

## Pedidos Collection [/pedidos]

### GET

+ Response 200 (application/json)
    + Attributes
        - pedidos (array[Pedido Full])

### POST

+ Request (application/json)
    + Attributes
        - pedidos (Pedido Create)

+ Response 200 (application/json)
    + Attributes
        - pedidos (Pedido Full)

## Pedido Resource [/pedidos/{id}]

+ Parameters
  + id: 1 - The unique ID of the pedido.

### GET

+ Response 200 (application/json)
    + Attributes
        - pedidos (Pedido Full)

### PUT

+ Request (application/json)
    + Attributes
        - pedidos (Pedido Full)

+ Response 200 (application/json)
    + Attributes
        - pedidos (Pedido Full)

### PATCH

+ Request (application/json)
    + Attributes
        - pedidos (Pedido Full)

+ Response 204 (application/json)

### DELETE

+ Response 204




# Group Anuncios

## Anuncios Collection [/anuncios]

### GET

+ Response 200 (application/json)
    + Attributes
        - anuncios (array[Anuncio Full])

### POST

+ Request (application/json)
    + Attributes
        - anuncios (Anuncio Create)

+ Response 200 (application/json)
    + Attributes
        - anuncios (Anuncio Full)

## Anuncio Resource [/anuncios/{id}]

+ Parameters
  + id: 1 - The unique ID of the anuncio.

### GET

+ Response 200 (application/json)
    + Attributes
        - anuncios (Anuncio Full)

### PUT

+ Request (application/json)
    + Attributes
        - anuncios (Anuncio Full)

+ Response 200 (application/json)
    + Attributes
        - anuncios (Anuncio Full)

### PATCH

+ Request (application/json)
    + Attributes
        - anuncios (Anuncio Full)

+ Response 204 (application/json)

### DELETE

+ Response 204

# Data Structures

## Comunidade Create (object)
Um grupo de comerciantes e consumidores.

## Properties
- nome: Parque de Ferraz de Vasconcelos (string, required) - Nome da comunidade.

## Comunidade Full (object)

## Properties
- id: 1 (number, required) - O identificador exclusivo de uma comunidade.
- nome: Parque de Ferraz de Vasconcelos (string, required) - Nome da comunidade.

## Categoria Create (object)
Um grupo de categorias.

## Properties
- nome: Alimentos (string, required) - Nome da categoria.

## Categoria Full (object)
Um grupo de categorias.

## Properties
- id: 1 (number, required) - O identificador exclusivo de uma categoria
- nome: Alimentos (string, required) - Nome da categoria.

## Comerciante Create (object)
Um fornecedor de produtos ou serviços para a comunidade.

## Properties
- nome: Pães dos Sonhos (string, required) - Nome fantasia do comerciante.
- comunidade: 10 (number, required) - Código da comunidade.

## Comerciante Full (object)
Um fornecedor de produtos ou serviços para a comunidade.

## Properties
- id: 1 (number, required) - O identificador exclusivo de um comerciante.
- nome: Pães dos Sonhos (string, required) - Nome fantasia do comerciante.
- comunidade: 10 (number, required) - Código da comunidade.

## Produto Create (object)
Um produto oferecido pelo comerciante.

## Properties
- nome: Pão integral (string, required) - Nome do produto.
- categoria: 10 (number, required) - Código da categoria.

## Produto Full (object)
Um produto oferecido pelo comerciante.

## Properties
- id: 10 (number, required) - O identificador exclusivo de um produto.
- nome: Pão integral (string, required) - Nome do produto.
- categoria: 10 (number, required) - Código da categoria.


## Servico Create (object)
Um serviço prestado pelo comerciante.

## Properties
- nome: Pintura da residência (string, required) - Nome da categoria.
- categoria: 10 (number, required) - Código da categoria.

## Servico Full (object)
Um serviço prestado pelo comerciante.

## Properties
- id: 1 (number, required) - O identificador exclusivo do serviço.
- nome: Pintura da residência (string, required) - Nome da categoria.
- categoria: 10 (number, required) - Código da categoria.


## Pedido Create (object)
Um pedido realizado pelo consumidor para um comerciante.

## Properties
- data: 10/08/2018 (string, required) - Data da criação do pedido.
- consumidor: 100 (number, required) - Código do consumidor responsável pelo pedido.
- comerciante: 1001 (number, required) - Código do comerciante responsável.

## Pedido Full (object)
Um pedido realizado pelo consumidor para um comerciante.

## Properties
- id: 1 (number, required) - O identificador exclusivo do pedido.
- data: 10/08/2018 (string, required) - Data da criação do pedido.
- consumidor: 100 (number, required) - Código do consumidor responsável pelo pedido.
- comerciante: 1001 (number, required) - Código do comerciante responsável.


## ItemProduto Create (object)
Um produto associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties
- pedido: 2001 (number, required) - Nome da categoria.
- produto: 10 (number, required) - Código do produto selecionado.
- quantidade: 1 (number, required) - Quantidade de produtos do pedido.
- preco: 12.50 (number, required) - Valor do produto.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.

## ItemProduto Full (object)
Um produto associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties
- id: 1 (number, required) - O identificador exclusivo do item.
- pedido: 2001 (number, required) - Nome da categoria.
- produto: 10 (number, required) - Código do produto selecionado.
- quantidade: 1 (number, required) - Quantidade de produtos do pedido.
- preco: 12.50 (number, required) - Valor do produto.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.

## ItemServiço Create (object)
Um serviço associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties
- pedido: 2001 (number, required) - Nome da categoria.
- serviço: 10 (number, required) - Código do serviço selecionado.
- quantidade: 1 (number, required) - Quantidade de serviços do pedido.
- preço: 12.50 (number, required) - Valor do serviço.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.

## ItemServiço Full (object)
Um serviço associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties
- id: 1 (number, required) - O identificador exclusivo do item.
- pedido: 2001 (number, required) - Nome da categoria.
- serviço: 10 (number, required) - Código do serviço selecionado.
- quantidade: 1 (number, required) - Quantidade de serviços do pedido.
- preço: 12.50 (number, required) - Valor do serviço.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.


## Anuncio Create (object)
Um anúncio para os consumidores da comunidade associada ao comerciante.

## Properties
- titulo: Oferta especial para venda (string, required) - O título do anúncio.
- comerciante: 10 (number, required) - O comerciante responsável pelo anuncio.

## Anuncio Full (object)
Um anúncio para os consumidores da comunidade associada ao comerciante.

## Properties
- id: 1 (number, required) - O identificador exclusivo do anuncio.
- titulo: Oferta especial para venda (string, required) - O título do anúncio.
- comerciante: 10 (number, required) - O comerciante responsável pelo anuncio.