FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Minha Comunidade API

Polls is a simple API allowing consumers to view polls and vote in them.

# Data Structures

# Comunidade
Um grupo de comerciantes e consumidores.

## Properties

- id: 1 (number, required) - O identificador exclusivo de uma comunidade
- nome: Parque de Ferraz de Vasconcelos (string, required) - Nome da comunidade


#Categoria
Um grupo de categorias.

## Properties

- id: 1 (number, required) - O identificador exclusivo de uma comunidade
- nome: Alimentos (string, required) - Nome da categoria.


#Comerciante
Um fornecedor de produtos ou serviços para a comunidade.

## Properties

- id: 1 (number, required) - O identificador exclusivo de uma comunidade
- nome: Pães dos Sonhos (string, required) - Nome fantasia do comerciante.
- comunidade: 10 (number, required) - Código da comunidade.

#Produto
Um produto oferecido pelo comerciante.

## Properties

- id: 10 (number, required) - O identificador exclusivo de uma comunidade
- nome: Pão integral (string, required) - Nome do produto.
- categoria: 10 (number, required) - Código da categoria.


#Servico
Um serviço prestado pelo comerciante.

## Properties

- id: 1 (number, required) - O identificador exclusivo do serviço.
- nome: Pintura da residência (string, required) - Nome da categoria.
- categoria: 10 (number, required) - Código da categoria.


#Pedido
Um pedido realizado pelo consumidor para um comerciante.

## Properties

- id: 1 (number, required) - O identificador exclusivo do pedido.
- data: 10/08/2018 (string, required) - Data da criação do pedido.
- consumidor: 100 (number, required) - Código do consumidor responsável pelo pedido.
- comerciante: 1001 (number, required) - Código do comerciante responsável.


#ItemProduto
Um produto associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties

- id: 1 (number, required) - O identificador exclusivo do item.
- pedido: 2001 (number, required) - Nome da categoria.
- produto: 10 (number, required) - Código do produto selecionado.
- quantidade: 1 (number, required) - Quantidade de produtos do pedido.
- preco: 12.50 (number, required) - Valor do produto.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.


#ItemServiço
Um serviço associado ao item do pedido realizado pelo consumidor para um comerciante.

## Properties

- id: 1 (number, required) - O identificador exclusivo de uma comunidade
- pedido: 2001 (number, required) - Nome da categoria.
- serviço: 10 (number, required) - Código do serviço selecionado.
- quantidade: 1 (number, required) - Quantidade de serviços do pedido.
- preço: 12.50 (number, required) - Valor do serviço.
- subtotal: 12.50 (number, required) - subtotal (quantidade * preço) do pedido.


#Anuncio
Um anúncio para os consumidores da comunidade associada ao comerciante.

## Properties

- id: 1 (number, required) - O identificador exclusivo do anuncio.
- titulo: Oferta especial para venda (string, required) - O título do anúncio.
- comerciante: 10 (number, required) - O comerciante responsável pelo anuncio.